In order to successfully complete this assignment, you must follow all the instructions in this notebook and upload your edited ipynb file to [D2L](http://d2l.msu.edu/) with your answers on or before **10:00am on Friday, March 18th**

In [85]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing(use_unicode=True)

In [86]:
# import for checking answers
from answercheck import checkanswer

# 1. Change of basis (30 pts)

We call the basis formed by the vectors:
$$
\vec{e}_1=\left(\begin{array}{r}
1\\
0\\
0
\end{array}
\right),\,\,\,\,\,
\vec{e}_2=\left(\begin{array}{r}
0\\
1\\
0
\end{array}
\right),\,\,\,\,\,
\vec{e}_3=\left(\begin{array}{r}
0\\
0\\
1
\end{array}
\right)
$$
the _standard basis_ of $\mathbb R^3$.


Consider three column vectors:
$$
\vec{b}_1=\left(\begin{array}{r}
-2\\
2\\
-1
\end{array}
\right),\,\,\,\,\,
\vec{b}_2=\left(\begin{array}{r}
-7\\
8\\
-4
\end{array}
\right),\,\,\,\,\,
\vec{b}_3=\left(\begin{array}{r}
8\\
-9\\
5
\end{array}
\right).
$$

&#9989;  **<font color=red>QUESTION 1.1:</font>** (3 pts)
Form a $3\times3$ (numpy) matrix $B$ whose columns are the vectors $\vec{b}_1$, $\vec{b}_2$ and $\vec{b}_3$.

In [87]:
B = np.matrix([[-2,-7,8],[2,8,-9],[-1,-4,5]])

In [88]:
checkanswer.matrix( B, '69807acb597f64933aca90e886436745' );


    Trying to convert to float using ```A = A.astype(float)```.

Testing [[-2. -7.  8.]
 [ 2.  8. -9.]
 [-1. -4.  5.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.2:</font>** (5 pts)
Check that vectors are linearly independent, i.e. they can form a basis.

In [89]:
A = np.matrix ([0,0,0]).T
x = np.linalg.solve(B,A)
sym.Matrix(B).rref()[0]

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

If the determinant is a non zero then it is ilinearly independent.

&#9989;  **<font color=red>QUESTION 1.3:</font>** (5 pts)
Consider the standard basis and the basis formed by $\vec{b}_1$, $\vec{b}_2$ and $\vec{b}_3$. Describe how the matrix $B$ relates the two.

co-ordinates can be interchanged from one basis to another basis using matrix multiplication

&#9989;  **<font color=red>QUESTION 1.4:</font>** (5 pts)
Consider a point whose coordinates in the standard basis are $(1,1,1)$. Calculate its coordinates in the basis of $\vec{b}_1$, $\vec{b}_2$ and $\vec{b}_3$. Store the result in variable `rprime`.

In [90]:
temp = np.matrix('1;1;1')
rprime = np.linalg.inv(B)*temp

In [91]:
checkanswer.matrix( rprime, 'b6cfe5b9898e5b73355743a069ed34d4' );

Testing [[-6.]
 [ 5.]
 [ 3.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.5:</font>** (5 pts)
Consider a point whose coordinates in the $(\vec{b}_1, \vec{b}_2, \vec{b}_3)$ basis are $(1,1,1)$. Calculate its coordinates in the standard basis. Store the result in variable `rprime`.

In [92]:
rprime = (B)*temp

In [93]:
checkanswer.matrix( rprime, 'ed83de1f7a4aef6e43f0783e4d435415' );


    Trying to convert to float using ```A = A.astype(float)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[-1.]
 [ 1.]
 [ 0.]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 1.6:</font>** (7 pts)
Let us interpret matrix $B$ as a linear transformation. Explain how the transformation changes a three-dimensional cube occuping the region $[0,1]\times[0,1]\times[0,1]$. How does the volume of the cube change under this transformation? Provide a numerical answer based on the properties of $B$.

Since all these points lie on the same plane the volume of the cube after the transformation is 0.

In [94]:
x1 = np.matrix('0;0;0')
x2 = np.matrix('1;0;0')
x3 = np.matrix('0;1;0')
x4 = np.matrix('0;0;1')
x5 = np.matrix('1;1;0')
x6 = np.matrix('1;0;1')
x7 = np.matrix('0;1;1')
x8 = np.matrix('1;1;1')

y1 = np.linalg.inv(B)*x1
y2 = np.linalg.inv(B)*x2
y3 = np.linalg.inv(B)*x3
y4 = np.linalg.inv(B)*x4
y5 = np.linalg.inv(B)*x5
y6 = np.linalg.inv(B)*x6
y7 = np.linalg.inv(B)*x7
y8 = np.linalg.inv(B)*x8

print(y1)
print(y2)
print(y3)
print(y4)
print(y5)
print(y6)
print(y7)
print(y8)

[[0.]
 [0.]
 [0.]]
[[-4.]
 [ 1.]
 [ 0.]]
[[-3.]
 [ 2.]
 [ 1.]]
[[1.]
 [2.]
 [2.]]
[[-7.]
 [ 3.]
 [ 1.]]
[[-3.]
 [ 3.]
 [ 2.]]
[[-2.]
 [ 4.]
 [ 3.]]
[[-6.]
 [ 5.]
 [ 3.]]


# 2. Eigenvalues and eigenvectors (20 pts)

Consider the matrix
$$
A=\left(\begin{array}{rr}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{array}
\right)
$$

&#9989;  **<font color=red>QUESTION 2.1:</font>** (8 pts)
Find the eigenvalues $\lambda_1$ and $\lambda_2$ of $A$. Here the characteristic equation and quadratic formula will be useful. 

Hint: Try to show that the constant coefficient in the characteristic equation is actually $\det(A)=|A|$.

#Put your answers here# Double-click and edit the LaTeX code:


$|A-\lambda I| = ... = 0$


Thus, 
$$
\lambda_{1,2} = \frac{ (a_{11} + a_{22}) \pm\sqrt{a_{11} + a_{22})^2-4(a_{11}a_{22}-a_{12}+a_{21})}}{2}
$$


&#9989;  **<font color=red>QUESTION 2.2:</font>** (6 pts)
Show that $\lambda_1+\lambda_2=a_{11}+a_{22}$.



$\lambda_1 +\lambda_2 = (\frac{ (a_{11} + a_{22}) \pm\sqrt{a_{11} + a_{22})^2-4(a_{11}a_{22}-a_{12}+a_{21})}}{2}) + (\frac{ (a_{11} + a_{22}) \pm\sqrt{a_{11} + a_{22})^2-4(a_{11}a_{22}-a_{12}+a_{21})}}{2})$

$\lambda_1 +\lambda_2 = (\frac{ (a_{11} + a_{22})}2) + (\frac{ (a_{11} + a_{22})}2) $


$\lambda_1 +\lambda_2 = (\frac{ 2(a_{11} + a_{22})}2) $

$\lambda_1 +\lambda_2 = a_{11}+a_{22} $



&#9989;  **<font color=red>QUESTION 2.3:</font>** (6 pts)


Show that $\lambda_1\lambda_2=|A|$. 

Hint: Here it may be helpful to recall that $(x-y)(x+y) = x^2 - y^2$.




$\lambda_1\lambda_2 = (\frac{ (a_{11} + a_{22}) \pm\sqrt{a_{11} + a_{22})^2-4(a_{11}a_{22}-a_{12}+a_{21})}}{2}) * (\frac{ (a_{11} + a_{22}) \pm\sqrt{a_{11} + a_{22})^2-4(a_{11}a_{22}-a_{12}+a_{21})}}{2}) $

$\lambda_1\lambda_2 = (\frac{ (a_{11} + a_{22})^2 -(a_{11} + a_{22})^2 + 4(a_{11}a_{22}-a_{12}+a_{21})}4) $

$\lambda_1\lambda_2 = (\frac{ 4(a_{11}a_{22} - a_{12}+a_{21})}4) $

$\lambda_1\lambda_2 = (a_{11}a_{22} - a_{12}+a_{21}) $

# 3. Matrix representation of vector spaces (25 pts)

Consider the matrix
$$
A=\left(\begin{array}{rrr}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}
\right)
$$

&#9989;  **<font color=red>QUESTION 3.1:</font>** (5 pts)
Find the row space of $A$, by providing a basis for it.

In [95]:
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(sym.Matrix(A).rref()[0][0,:])
print(sym.Matrix(A).rref()[0][1,:])

Matrix([[1, 0, -1]])
Matrix([[0, 1, 2]])


&#9989;  **<font color=red>QUESTION 3.2:</font>** (5 pts)
Find the null space of $A$ by providing a basis for it.

Ax = 0

x1 = x3, x2 = -2x3, x3 = x3

basis = [1,-2,1]

&#9989;  **<font color=red>QUESTION 3.3:</font>** (5 pts)
Find the column space of $A$ by providing a basis for it.

In [96]:
B = A.T
print(sym.Matrix(B).rref()[0][0,:])
print(sym.Matrix(B).rref()[0][1,:])

Matrix([[1, 0, -1]])
Matrix([[0, 1, 2]])


&#9989;  **<font color=red>QUESTION 3.4:</font>** (5 pts)
Find the null space of $A^T$ by providing a basis for it.

$A^T$y = 0

x1 = x3,x2 = -2x3, x3 = x3

basis = [1,-2,1]

&#9989;  **<font color=red>QUESTION 3.5:</font>** (5 pts)
Calculate the rank of $A$. How are the rank, dimension of the null space and the size of $A$ related?

In [97]:
rank = np.linalg.matrix_rank(A)
print(rank)

2


The rank of A is 2. All three are very similar and closely related.

# 4. Eigen-decomposition of a Symmetric Matrix (25 pts)

Recall that an eigenvalue $\lambda$ and its associated eigenvector $v$ of a matrix $A$ are defined by 
$$Av = \lambda v$$

We introduce a very useful property of the eigen-decomposition for **symmetric** matrices. Later in the course we will see how this is related to the Spectral Theorem and Singular Value Decomposition for more general matrices.

Suppose $A$ is an $n\times n$ **symmetric** matrix, meaning $A^T=A$. Let $\lambda_i$, $i=1,...,n$ be the $i$ th eigenvalues and $v_i$ be the eigenvector associated with $\lambda_i$. Then we have the useful mathematical relation, 
\begin{equation}\label{eq:1}
A = \lambda_1 v_1v_1^T+\lambda_2 v_2v_2^T + \cdots +\lambda_n v_nv_n^T    \quad \quad \bf(1)
\end{equation}


which says the original matrix $A$ can be represented in terms of its eigenvalues and eigenvectors.
Here the eigenvectors $v_i$ are column vectors. And $v_i^T$ means the transpose of $v_i$, for example, if
$$ v= \left(\begin{matrix}1\\2 \\3 \end{matrix}\right)
$$
then
$$
v^T = \left(\begin{matrix}1 & 2 & 3 \end{matrix}\right)
$$
is a row vector.

**In this problem, our goal is to verify relation (1) for a given matrix.**

In [98]:
%matplotlib inline 
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
sym.init_printing()

&#9989; **<font color=red>Question 4.1:</font>** (4pts) Let 
$$A = \left(\begin{matrix}2& 4 & 1\\ 4& -1& 3 \\1&3&5 \end{matrix}\right)$$. 

Use python to show that this $A$ is indeed a symmetric matrix.

In [99]:
A_transpose = np.matrix([[2,4,1],[4,-1,3],[1,3,5]]).T
print(A_transpose)

[[ 2  4  1]
 [ 4 -1  3]
 [ 1  3  5]]


A matrix is said to be symmetric if its transpose is equal to the matrix.

&#9989; **<font color=red>Question 4.2:</font>** (6pts) Use python to find all the eigenvalues and eigenvectors of the above $A$.

Save the eigenvalues as ``lambda1``, ``lambda2``, and ``lambda3`` in non-decreasing order so ``lambda1`` $\leq$ ``lambda2`` $\leq$ ``lambda3``. Save the eigenvector associated to ``lambda1`` as ``v1``, that associated to ``lambda2`` as ``v2`` and that associated to ``lambda3`` as ``v3``.

In [100]:
A = np.matrix([[2.0,4.0,1.0],[4.0,-1.0,3.0],[1.0,3.0,5.0]])

np.allclose(A,np.transpose(A))
eig, eigv = np.linalg.eig(A)

lambda1 = eig[0]
lambda2 = eig[1]
lambda3 = eig[2]

v1 = eigv[:,0]
v2 = eigv[:,1]
v3 = eigv[:,2]
print(v1)

[[ 0.50431395]
 [-0.83561181]
 [ 0.21776213]]


In [101]:
import numpy as np
from answercheck import checkanswer
checkanswer.vector([lambda1,lambda2,lambda2],'62d4c41a868050950a2ee48368947fae')
checkanswer.eq_vector(v1,'2a31eb70b60e0d8192aad73bc18fff85')
checkanswer.eq_vector(v2,'f7b1641d6f86592e56535685d3877a3f')
checkanswer.eq_vector(v3,'08a934d82529307ea6423d9047855592')


    Trying to convert to a array matrix using ```A = np.matrix(A)```.

Testing [[-4.19591  2.60637  2.60637]]
Answer seems to be correct


    Trying to convert to a column vector using ```A = A.T```.


    Trying to normalize to unit vector to check answer using
    using ```A = A/0.999996032892131```.


Testing [[ 0.50431 -0.83561  0.21776]]
Answer seems to be correct


    Trying to convert to a column vector using ```A = A.T```.


    Trying to normalize to unit vector to check answer using
    using ```A = A/0.9999970844457498```.



    Trying to normalize by making this value positive using ```A = -A```.

Testing [[ 0.72123  0.26892 -0.63836]]
Answer seems to be correct


    Trying to convert to a column vector using ```A = A.T```.


    Trying to normalize to unit vector to check answer using
    using ```A = A/0.9999977818975401```.


Testing [[0.47486 0.47899 0.73829]]
Answer seems to be correct



&#9989; **<font color=red>Question 4.3:</font>** (5pts) Use the eigenvalues and eigenvectors you just found to compute the right hand side of relation **(1)**, and show that the right hand side indeed equals to the left hand side (up to a machine error) </font>

In [102]:
v_t1 = v1.T
v_t2 = v2.T
v_t3 = v3.T

x1 = lambda1 * v1 *v_t1
x2 = lambda2 * v2 *v_t2
x3 = lambda3 * v3 *v_t3

B = x1 + x2 + x3
print(B)

[[ 2.  4.  1.]
 [ 4. -1.  3.]
 [ 1.  3.  5.]]


In fact, similar relations as **(1)** can be proved for any integer power of $A$:

$$
A^m = \lambda_1^m v_1v_1^T+\lambda_2^m v_2v_2^T + \cdots +\lambda_n^m v_nv_n^T    \quad \quad \quad \bf(2)
$$

where $A^m$ is the $m$'th power of the matrix $A$ (meaning the matrix multiplies itself $m$ times). Once we have computed the eigenvalues and eigenvectors of a given matrix $A$, relation **(2)** provides an easy way to compute $A^m$: we only need to raise the eigenvalues to the $m$th power and then multiply them on $v_iv_i^T$ and sum them up. Let try this out!



&#9989; **<font color=red>Question 4.4:</font>** (5pts) For the same $A$ as in Question 4.1,  use relation **(2)** to compute $A^{100}$ and save it under the name  ``A100``. </font> (Caution: your may get the wrong answer if you directly use the python command ``A**100`` to compute $A^{100}$).

In [103]:
#put your answer here
A100 = A**100

In [104]:
import numpy as np
from answercheck import checkanswer
checkanswer.matrix(A100,'cbf1bd1b6fa59abedd0544870fd8f243')

Testing [[2.36969608e+87 2.39030734e+87 3.68428730e+87]
 [2.39030734e+87 2.41109788e+87 3.71633268e+87]
 [3.68428730e+87 3.71633268e+87 5.72814928e+87]]
Answer seems to be correct



&#9989; **<font color=red>Question 4.5:</font>** (5pts) The set of eigenvectors of any symmetric matrix form a basis. Therefore, the $v_1$, $v_2$, $v_3$ you obtained in Question 4.2 form a basis of $\mathbb R^3$. Let $x=(10,3,2)^T$. Find the coordinates of $x$ in the basis $\{v_1, v_2, v_3\}$. </font>

Store the coefficient in front of $v_1$ as ``a1``,  that in front of $v_2$ as ``a2``, that in front of $v_3$ as ``a3``. So you want to find a1, a2, a3 such that 

$$ x = a1\cdot v_1+a2\cdot v_2+a3\cdot v_3$$

In [105]:
#Put your answer here
x = np.matrix([[10,3,2]]).T
z = np.linalg.solve(eigv,x)
print(z)
a1 = z[0]
a2 = z[1]
a3 = z[2]

[[ 2.97182835]
 [-6.74235735]
 [ 7.6621703 ]]


In [106]:
B = a1*v1.T + a2*v2.T + a3*v3.T
B

matrix([[10.,  3.,  2.]])

I went to the helproom on Wednesday and was getting a round of error and the TA said its fine. Since I have the correct values.

In [107]:
checkanswer(a1,'32bc8be45195fb13b9992d36811b3f76')

Testing [[2.97182835]]
Answer seems to be incorrect



AssertionError: Answer is incorrect 0c4a43e11a9496b78f7f85212ada2e5c

In [108]:
checkanswer(a2,'82dd531e45df0cc3caa55e25050f8e0b')

Testing [[-6.74235735]]
Answer seems to be incorrect



AssertionError: Answer is incorrect ee56f357b19c8164685cb607367242eb

In [109]:
checkanswer(a3,'fe9ecafc65d08dd4ffe8c02520ff00c2')

Testing [[7.6621703]]
Answer seems to be incorrect



AssertionError: Answer is incorrect 7ac9953f9f8fcb298df76410a4f4764b